# Default values for bifrost.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: openresty/openresty
  tag: alpine-fat
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  #type: NodePort
  #type: ClusterIP
  #type: NodePort
  type: LoadBalancer
  port: 443
  loadBalancerIP: 35.200.156.113 # needs to be created

bifrost:
  tls:
    certificate: config/nginx/ssl/localhost.crt
    key: config/nginx/ssl/localhost.key
  routes_json: config/nginx/routes.json


ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
