apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl
type: Opaque
data:
  {{ $certificate := .Values.bifrost.tls.certificate }}
  {{ $key_file := .Values.bifrost.tls.key }}
  localhost.crt: |- 
    {{- (.Files.Glob $certificate).AsSecrets | nindent 2 }}
  localhost.key: |-
    {{- (.Files.Glob $key_file).AsSecrets | nindent 2 }}
