apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl
type: Opaque
data:
  localhost.crt: |- 
    {{- (.Files.Glob "config/nginx_conf.d/ssl/localhost.crt").AsSecrets | nindent 2 }}
  localhost.key: |-
    {{- (.Files.Glob "config/nginx_conf.d/ssl/localhost.key").AsSecrets | nindent 2 }}

